# Настройки frontend приложения
frontend:
  host: 'localhost:5173'

# Настройки gateway приложения
gateway:
  port: 3001

# Настройки микросервисов
microservices:
  users:
    host: 'localhost'
    port: 3002
    access-expires-in: 180000
    refresh-expires-in: 360000
